version: '3'
services:
  ypt-bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    command: python app.py
